Organizations:
  - &OrdererOrg
    Name: Orderer
    ID: ordererMSP
    MSPDir: crypto-config/ordererOrganizations/pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererMSP.member')"

  - &ManufacturerOrg
    Name: Manufacturer
    ID: manufacturerMSP
    MSPDir: crypto-config/peerOrganizations/manufacturer.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('manufacturerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('manufacturerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('manufacturerMSP.member')"
    AnchorPeers:
      - Host: peer0.manufacturer.pharma-network.com
        Port: 7051

  - &DistributorOrg
    Name: Distributor
    ID: distributorMSP
    MSPDir: crypto-config/peerOrganizations/distributor.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('distributorMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('distributorMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('distributorMSP.member')"
    AnchorPeers:
      - Host: peer0.distributor.pharma-network.com
        Port: 9051

  - &TransporterOrg
    Name: Transporter
    ID: transporterMSP
    MSPDir: crypto-config/peerOrganizations/transporter.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('transporterMSP.client', 'transporterMSP.peer', 'transporterMSP.admin' )"
      Writers:
        Type: Signature
        Rule: "OR('transporterMSP.client', 'transporterMSP.peer', 'transporterMSP.admin' )"
      Admins:
        Type: Signature
        Rule: "OR('transporterMSP.client', 'transporterMSP.peer', 'transporterMSP.admin' )"
    AnchorPeers:
      - Host: peer0.transporter.pharma-network.com
        Port: 11051

  - &RetailerOrg
    Name: Retailer
    ID: retailerMSP
    MSPDir: crypto-config/peerOrganizations/retailer.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('retailerMSP.client', 'retailerMSP.admin', 'retailerMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('retailerMSP.client', 'retailerMSP.admin', 'retailerMSP.peer')"
      Admins:
        Type: Signature
        Rule: "OR('retailerMSP.client', 'retailerMSP.admin', 'retailerMSP.peer')"
    AnchorPeers:
      - Host: peer0.retailer.pharma-network.com
        Port: 13051

  - &ConsumerOrg
    Name: Consumer
    ID: consumerMSP
    MSPDir: crypto-config/peerOrganizations/consumer.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('consumerMSP.client', 'consumerMSP.admin', 'consumerMSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('consumerMSP.client', 'consumerMSP.admin', 'consumerMSP.peer')"
      Admins:
        Type: Signature
        Rule: "OR('consumerMSP.client', 'consumerMSP.admin', 'consumerMSP.peer')"
    AnchorPeers:
      - Host: peer0.consumer.pharma-network.com
        Port: 15051

# Capabilities
Capabilities:
  Channel: &ChannelCapabilities
    V1_4_2: true
    V1_3: false
    V1_1: false
  Application: &ApplicationCapabilities
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false
  Orderer: &OrdererCapabilities
    V1_4_2: true
    V1_1: false

Application: &ApplicationDefaults
  Policies: &ApplicationDefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.pharma-network.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99MB
    PreferredMaxBytes: 512KB
  Capabilities:
    <<: *OrdererCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      PharmaNetConsortium:
        Organizations:
          - *ManufacturerOrg
          - *DistributorOrg
          - *TransporterOrg
          - *RetailerOrg
          - *ConsumerOrg

  PharmaChannel:
    Consortium: PharmaNetConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ManufacturerOrg
        - *DistributorOrg
        - *TransporterOrg
        - *RetailerOrg
        - *ConsumerOrg
      Capabilities:
        <<: *ApplicationCapabilities
