OrdererOrgs:
  - Name: Orderer
    Domain: drug-counterfeit-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Distributor
    Domain: distributor.drug-counterfeit-network.com
    EnableOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: Manufacturer
    Domain: manufacturer.drug-counterfeit-network.com
    EnableOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: Transporter
    Domain: transporter.drug-counterfeit-network.com
    EnableOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: Retailer
    Domain: retailer.drug-counterfeit-network.com
    EnableOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
  - Name: Consumer
    Domain: consumer.drug-counterfeit-network.com
    EnableOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
